[package]
name = "collatz-sequence"
version = "0.1.0"
edition = "2021"
author = "Ferdinand Keller"
license = "MIT"
description = "An algorithm for computing the Collatz sequence"

[dependencies]
num-bigint = "0.4"
num-format = { version = "0.4", features = ["with-num-bigint"] }